### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by leifdenby** [leifdenby/python-cloudmodel#2]
Clean up notebooks:

in `notebooks/`:
- [ ] Cloud model integration - effect of entrainment.ipynb
- [ ] Cloud model integration.ipynb
- [ ] Cloud model integration - moist.ipynb
- [ ] Cloud model integration - rain condevap.ipynb
- [ ] cloudphysics.f90 re-implementation.ipynb
- [ ] Condensation rate for rising parcel.ipynb
- [ ] Droplet growth rate.ipynb
- [ ] Entrainment contribution terms - dry plume.ipynb
- [ ] Entrainment contribution terms - moist plume.ipynb
- [ ] Fortran + Python microphysics integration.ipynb
- [ ] In-cloud lapse rate.ipynb
- [ ] __init__.py
- [ ] Integration methods.ipynb
- [ ] Microphysics integration.ipynb
- [ ] Microphysics integration- raind condevap.ipynb
- [ ] Moisture adjusted lapse rate.ipynb
- [ ] Multivariable adaptive integration.ipynb
- [ ] New droplet-formation model.ipynb
- [ ] Preparing input for cloud-model integration.ipynb
- [ ] Python wrappers for microphysics routines.ipynb
- [ ] Saturation adjustment.ipynb
- [ ] Timestep size and stability.ipynb
- [ ] Untitled1.ipynb
- [ ] Untitled.ipynb
